title: দৈনিক চালচিত্র
description: ওমান থেকে প্রকাশিত অনলাইন পত্রিকা - বাংলাদেশের জনপ্রিয় অনলাইন নিউজপেপার
baseurl: ""
url: "https://www.dailychalchitra.com"
timezone: Asia/Muscat
markdown: kramdown
permalink: pretty
future: true

plugins:
        - jekyll-seo-tag
        - jekyll-sitemap
        - jekyll-redirect-from

include:
    - ads.txt
    - _redirects
    - CNAME

webmaster_verifications:
  google: O6AQ_cAwG8RoU5yHbkg7QvLF8daax_FglyiF2XMinBg

kramdown:
  input: GFM
  hard_wrap: true
