title: দৈনিক চালচিত্র
description: ওমান থেকে প্রকাশিত অনলাইন পত্রিকা
baseurl: ""
url: "https://dailychalchitra.com"
markdown: kramdown
permalink: pretty
future: true
kramdown:
  input: GFM
  hard_wrap: true
