backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "blog"
    label: "নিউজ পোস্ট"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - label: "তারিখ"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss Z"
        picker_utc: false
            - {label: "ফিচার ছবি", name: "thumbnail", widget: "image"}
            - {label: "মূল ক্যাটাগরি", name: "categories", widget: "select", options: ["বাংলাদেশ", "বিশ্ব", "সংবাদ", "সাহিত্য বিভাগ", "বিনোদন", "শিক্ষা", "খেলাধুলা", "জীবনযাপন", "চাকরির বিজ্ঞপ্তি", "বাণিজ্য", "ধর্ম বিষয়ক", "বিভাগ সমূহ", "মতামত", "অন্যান্য", "আরও"]}
            - {label: "সাব ক্যাটাগরি", name: "tags", widget: "select", options: ["সর্বশেষ", "রাজধানী", "জেলা", "করোনাভাইরাস", "পরিবেশ", "অপরাধ", "ভারত", "পাকিস্তান", "চীন", "ইরান", "সৌদি আরব", "যুক্তরাষ্ট্র", "যুক্তরাজ্য", "এশিয়া", "ইউরোপ", "আফ্রিকা", "লাতিন আমেরিকা", "দেশের সংবাদ", "আন্তর্জাতিক", "নিখোঁজ সংবাদ", "শোক সংবাদ", "জরুরী সংবাদ", "কবিতা", "পদ্য কবিতা", "গদ্য কবিতা", "ছড়া কবিতা", "অনু কবিতা", "সনেট কবিতা", "লিমেরিক কবিতা", "বড় গল্প", "ছোট গল্প", "অনু গল্প", "সামাজিক গল্প", "ভালোবাসার গল্প", "জীবনমুখী গল্প", "প্রবন্ধ ও নিবন্ধ", "রম্যরচনা", "কৌতুক", "ভ্রমণ", "মুক্ত গদ্য", "বই পরিচিতি", "সামাজিক উপন্যাস", "ঐতিহাসিক উপন্যাস", "মনস্তাত্ত্বিক উপন্যাস", "রহস্য উপন্যাস", "রাজনৈতিক উপন্যাস", "রূপক উপন্যাস", "পত্রোপন্যাস", "হাস্যরসাত্মক উপন্যাস", "মায়ের চিঠি", "বাবার চিঠি", "ভাইয়ের চিঠি", "বোনের চিঠি", "বন্ধুর চিঠি", "প্রেমের চিঠি", "প্রবাসী চিঠি", "শেষ চিঠি", "উক্তি", "গান", "চলচ্চিত্র", "টেলিফিল্ম", "নাটক", "সংলাপ", "শিল্পকলা", "বিজ্ঞাপন", "ভর্তি", "পরীক্ষা", "বৃত্তি", "পড়াশোনা", "উচ্চশিক্ষা", "ক্যাম্পাস", "ফুটবল", "ক্রিকেট", "হা-ডু-ডু", "বাস্কেটবল", "ভলিবল", "টেনিস", "ব্যাডমিন্টন", "হকি", "বেসবল", "অ্যাথলেটিক্স", "টেবিল টেনিস", "রাগবি", "গলফ", "সাঁতার", "কুস্তি", "দাবা", "সুস্থতা", "সম্পর্ক", "রূপচর্চা", "গৃহসজ্জা", "কেনাকাটা", "চাকরির খবর", "নিয়োগ", "চাকরির পরামর্শ", "সাক্ষাৎকার", "শেয়ারবাজার", "ব্যাংক", "শিল্প", "অর্থনীতি", "বিশ্ব বাণিজ্য", "বিশ্লেষণ", "ব্যক্তিগত অর্থ", "উদ্যোক্তা", "করপোরেট", "বাজেট", "ইসলাম", "সনাতন", "বৌদ্ধ", "খ্রিস্টান", "ঐতিহ্যবাহী / জাতিগত ধর্ম", "নাস্তিক", "ঢাকা", "চট্টগ্রাম", "রাজশাহী", "খুলনা", "বরিশাল", "সিলেট", "রংপুর", "ময়মনসিংহ", "সম্পাদকীয়", "কলাম", "স্মরণ", "প্রতিক্রিয়া", "আলোচনা", "সমালোচনা", "গোলটেবিল", "বিশেষ সংখ্যা", "অনলাইন ভোট", "প্রতিষ্ঠা বার্ষিকী"]}
            - {label: "বিস্তারিত", name: "body", widget: "markdown"}
